### ISSUE TITLE
Either try or catch, both: try ... catch

### ISSUE THREAD

**Issue by renerocksai** [rdoetjes/tuts#1]
https://github.com/rdoetjes/tuts/blob/b5db9efa458c5b764a00139851b05399e58d6456/smac/src/smac_st_net.zig#LL23C5-L23C8

I'm curious how this compiled at all, yet I think I saw it in the video. You're probably aware that you usually either `try foo();` or `foo() catch unreachable;`. I'm too lazy to submit a PR :smile:. Might send you one when I am at my computer.

**Comment by rdoetjes** [comment]
Thanks Rene!I’m also amazed that this compiled because the try shouldn’t be there!Well spotted! Thanks I’ll update it.Sent from my iPhoneOn 8 May 2023, at 10:13, Rene Schallner ***@***.***> wrote:﻿
https://github.com/rdoetjes/tuts/blob/b5db9efa458c5b764a00139851b05399e58d6456/smac/src/smac_st_net.zig#LL23C5-L23C8
I'm curious how this compiled at all, yet I think I saw it in the video. You're probably aware that you usually either try foo(); or foo() catch unreachable;. I'm too lazy to submit a PR 😄. Might send you one when I am at my computer.

**Comment by rdoetjes** [comment]
Ooh no the try is for the server.listen the catch unreachable is for the parseIp.I did however still have the for loop in this one changed that for all the 0.10.X users so still something good came from your comment.Thanks! I love how people think alone and improve content.Cheers,RaySent from my iPhoneOn 8 May 2023, at 10:41, Raymond Doetjes ***@***.***> wrote:﻿Thanks Rene!I’m also amazed that this compiled because the try shouldn’t be there!Well spotted! Thanks I’ll update it.Sent from my iPhoneOn 8 May 2023, at 10:13, Rene Schallner ***@***.***> wrote:﻿
https://github.com/rdoetjes/tuts/blob/b5db9efa458c5b764a00139851b05399e58d6456/smac/src/smac_st_net.zig#LL23C5-L23C8
I'm curious how this compiled at all, yet I think I saw it in the video. You're probably aware that you usually either try foo(); or foo() catch unreachable;. I'm too lazy to submit a PR 😄. Might send you one when I am at my computer.

**Comment by renerocksai** [comment]
Man, how could I miss that? Sorry for the inconvenience caused. Yet, it seems to have lead to a positive outcome after all! :+1:
