### ISSUE TITLE
Not printing to socket?

### ISSUE THREAD

**Issue by ssantoshp** [rdoetjes/tuts#2]
Hey, I am coming from your video about making SMAC in Zig, and I had trouble making the smac_st_net.zig running. I was wondering if you could help me understand why? Your video is my first introduction to Zig, and I wanted to follow the code to get to know it a bit more; awesome content!

So I tried the same code as the repo (I thought I missed something when coding along), but I got this error:
```zig
smac_net.zig:36:28: error: no field or member function named 'writeAll' in 'net.Stream'
        _ = try conn.stream.writeAll(item);
                ~~~~~~~~~~~^~~~~~~~~
/opt/homebrew/Cellar/zig/0.10.1/lib/zig/std/net.zig:1626:20: note: struct declared here
pub const Stream = struct {
                   ^~~~~~
```

Then, when replacing `writeAll` by `write`, it compiles well, but when running, nothing prints after it starts the socket and show the listening message when I run the executable. Am I doing something wrong, or do you see where this could be fixed? Best and keep up with the good content!

**Comment by rdoetjes** [comment]
What version are you using?This was written on 0.10 I noticed that the language is moving a lot, and it seems that you may run 0.11 where they apparently removed wtiteAll.Sent from my iPhoneOn 22 Jul 2023, at 05:05, Santosh Passoubady ***@***.***> wrote:﻿
Hey, I am coming from your video about making SMAC in Zig, and I had trouble making the smac_st_net.zig running. I was wondering if you could help me understand why? Your video is my first introduction to Zig, and I wanted to follow the code to get to know it a bit more; awesome content!
So I tried the same code as the repo (I thought I missed something when coding along), but I got this error:
smac_net.zig:36:28: error: no field or member function named 'writeAll' in 'net.Stream'
        _ = try conn.stream.writeAll(item);
                ~~~~~~~~~~~^~~~~~~~~
/opt/homebrew/Cellar/zig/0.10.1/lib/zig/std/net.zig:1626:20: note: struct declared here
pub const Stream = struct {
                   ^~~~~~
Then, when replacing writeAll by write, it compiles well, but when running, nothing prints when I run the executable. Am I doing something wrong, or do you see where this could be fixed? Best and keep up with the good content!

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by rdoetjes** [comment]
The code needs to be compiled using Zig 0.11
